version: 1
services:
  # Основной веб-сервис
  - type: web
    name: emotional-ai-web
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r web-service/requirements.txt
    startCommand: cd web-service && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emotional-ai-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: AI_SERVICE_URL
        fromService:
          type: web
          name: emotional-ai-service
          envVarKey: RENDER_EXTERNAL_URL
      - key: LOG_LEVEL
        value: INFO

  # AI микросервис
  - type: web
    name: emotional-ai-service
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r ai-service/requirements.txt
    startCommand: cd ai-service && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: HF_HOME
        value: /tmp/huggingface
      - key: TRANSFORMERS_CACHE
        value: /tmp/huggingface

  # База данных PostgreSQL
  - type: postgres
    name: emotional-ai-db
    region: frankfurt
    plan: free
    ipAllowList: []
    databaseName: emotional_ai
    user: emotional_ai_user