services:
  - type: web
    name: ai-personality-service
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import app, db; app.app_context().push(); db.create_all()"
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: personality-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0

databases:
  - name: personality-db
    plan: free
    databaseName: personality
    user: personality_user